FROM debian:jessie

#ENV REPO=apache/trafficserver
#ENV REF=6c1c6cf20e7d0e287d697a0f4181436013d17c30

# for testing cache-key-genid fix
ENV REPO=torchbox/trafficserver
ENV REF=889f5b4c27fe8d9cb1c6d4663826730e441bd58a

ENV LANG C.UTF-8

RUN	set -ex									\
	&& apt-get update							\
	&& apt-get -y install tar gcc bzip2 libc6-dev linux-libc-dev make curl	\
		libncursesw5-dev openssl libssl-dev zlib1g-dev libpcre3-dev	\
		perl libxml2-dev libcap-dev tcl8.6-dev libhwloc-dev		\
		libgeoip-dev libmysqlclient-dev libkyotocabinet-dev		\
		libreadline-dev autoconf automake				\
	&& mkdir -p /usr/src							\
	&& cd /usr/src								\
	&& curl -L https://github.com/${REPO}/archive/${REF}.tar.gz | gzip -dc | tar xf -

COPY config.layout /usr/src/trafficserver-${REF}

RUN	set -ex									\
	&& cd /usr/src/trafficserver-${REF}					\
	&& autoreconf -if							\
	&& env LDFLAGS='-Wl,-rpath,/usr/local/lib' ./configure			\
		--enable-wccp --enable-hardening --enable-luajit		\
		--enable-tproxy --enable-experimental-plugins			\
		--enable-layout=Torchbox					\
	&& make -j$(getconf _NPROCESSORS_ONLN)					\
	&& make install								\
	&& rm -rf /usr/src/

CMD ["/usr/local/bin/traffic_cop", "-o"]
