FROM debian:jessie

ENV REF=8dc35e04a8a0b4fb6b1ea2bebcfaa915e7acdbf5
ENV LANG C.UTF-8

RUN	set -ex									\
	&& apt-get update							\
	&& apt-get -y install tar gcc bzip2 libc6-dev linux-libc-dev make curl	\
		libncursesw5-dev openssl libssl-dev zlib1g-dev libpcre3-dev	\
		perl libxml2-dev libcap-dev tcl8.6-dev libhwloc-dev		\
		libgeoip-dev libmysqlclient-dev libkyotocabinet-dev		\
		libreadline-dev autoconf automake				\
	&& mkdir -p /usr/src							\
	&& cd /usr/src								\
	&& curl -L https://github.com/apache/trafficserver/archive/${REF}.tar.gz | gzip -dc | tar xf -

COPY config.layout /usr/src/trafficserver-${REF}

#		--prefix=/usr/local						\
#		--sysconfdir=/usr/local/etc/trafficserver			\
#		--localstatedir=/var/lib/trafficserver				\

RUN	set -ex									\
	&& cd /usr/src/trafficserver-${REF}					\
	&& autoreconf -if							\
	&& env LDFLAGS='-Wl,-rpath,/usr/local/lib' ./configure			\
		--enable-wccp --enable-hardening --enable-luajit		\
		--enable-tproxy --enable-experimental-plugins			\
		--enable-layout=Torchbox					\
	&& make -j$(getconf _NPROCESSORS_ONLN)					\
	&& make install								\
	&& rm -rf /usr/src/

CMD ["/usr/local/bin/traffic_cop", "-o"]
